CREATE TABLE `table_1`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE `table_2`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE `table_3`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `table_1` ADD CONSTRAINT `table_1_id_foreign` FOREIGN KEY(`id`) REFERENCES `table_2`(`id`);
ALTER TABLE
    `table_2` ADD CONSTRAINT `table_2_id_foreign` FOREIGN KEY(`id`) REFERENCES `table_3`(`id`);