CREATE TABLE `table_1`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE `table_2`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
ALTER TABLE
    `table_2` ADD CONSTRAINT `table_2_id_foreign` FOREIGN KEY(`id`) REFERENCES `table_1`(`id`);